// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller"
application.register("form", FormController)

import NotificationsController from './notifications_controller'
application.register('notifications', NotificationsController)
